yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
POST_STR = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:POST_STR]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Комментарий', help_text='Оставьте комментарий')
    created = models.DateTimeField('Дата и время публикации',
                                   auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User,
                             verbose_name='Подписчик',
                             related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор',
                               related_name='following',
                               on_delete=models.CASCADE)

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import paginate_posts


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('group')
    page_obj = paginate_posts(request, posts)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate_posts(request, posts)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginate_posts(request, posts)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {'author': author, 'page_obj': page_obj, 'following': following}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post_id=post.id)
    form = CommentForm()
    context = {'post': post, 'comments': comments, 'form': form}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=post.author)
    form = PostForm()
    return render(request, 'posts/create_post.html',
                  {'form': form, 'username': request.user})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'post': post, 'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    page_obj = paginate_posts(request, posts)
    return render(request, 'posts/follow.html', {'page_obj': page_obj})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (Follow.objects.filter(author=author, user=request.user).exists()
            or request.user == author):
        return redirect('posts:profile', username=username)
    Follow.objects.create(author=author, user=request.user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if (Follow.objects.filter(author=author, user=request.user).exists()
            and request.user != author):
        following = Follow.objects.get(author=author, user=request.user)
        following.delete()
        return redirect('posts:profile', username=username)
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{%extends 'base.html'%}
    <title> {% block title%} Новый пост {% endblock%} </title>
    {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">   
                {% if is_edit %}
                    Редактировать запись
                  {% else %}
                    Добавить запись
                  {% endif %}              
              </div>
              {% if is_edit %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.id %}">
                {% csrf_token %} 
                <div class="form-group row my-3 p-3">
                 {{ form.as_p }}
                </div>
                {%else%}
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
                   {% csrf_token %} 
                   <div class="form-group row my-3 p-3">
                   {{form.as_p}}
                   </div>
                  {%endif%}
                  <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{%extends 'base.html'%}
{% load thumbnail %}
    <title> {% block title %} Подписки пользователя {% endblock %} </title>
    <main> 
    {% block content %}
    <div style= "margin-left: 20;padding-left: 20;"   >     
        {% include 'posts/includes/switcher.html' %}
    </div>
      <div class="container py-5">     
        <h2>Подписки пользователя {{user.username}} </h2>
        <article>
          {% for post in page_obj %}
           <ul>
             <li>
               Автор: {{ post.author.get_full_name }}
             </li>
             <li>
               Дата публикации: {{ post.pub_date|date:"d E Y" }}
             </li>
           </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>  
            <a href= "{% url 'posts:post_detail' post.id %}"> Подробная информация </a>  <br>
          {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          {% endif %} 
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        </article>
        {% include 'posts/includes/paginator.html' %}
         </div>  
    {% endblock %} 
    </main>

yatube/templates/posts/group_list.html
    {% extends 'base.html' %}
    {% load thumbnail %}
    <title>{% block title %}Записи сообщества {{group}}{% endblock %} </title>
    <main>
    {% block content %}
      <div class="container py-5">
        <header><h1> {%block header %}{{group.title}}{% endblock%}</h1> </header>
        <p> 
          {{group.description}}
        </p>
        <article>
          {% for post in page_obj %}
           <ul>
             <li>
               Автор: {{ post.author.get_full_name }}
             </li>
             <li>
               Дата публикации: {{ post.pub_date|date:"d E Y" }}
             </li>
           </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>   
          <a href="{% url 'posts:post_detail' post.id %}">Подробнее</a> 
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div>  
      {% endblock %} 
    </main>
   

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <article>
  {% for post in page_obj %} 
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul> 
  <p>{{ post.text }}</p>  
  <a href= "{% url 'posts:post_detail' post.id %}"> Подробная информация </a>  <br>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</article>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{%extends 'base.html'%}
{% load thumbnail %}
    <title>{%block title %} Пост {{post|truncatechars:30}} {% endblock %}</title>
    <main>
    {%block content %} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %} 
            <li class="list-group-item">
              Группа: {{post.group.title}}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} 
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{post.author.posts.count}}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
            </li>
            <li class="list-group-item">
              <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">Редактировать запись </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{post.text}}</p>
        </article>
      </div> 
      {% load user_filters %}
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
           <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group row my-3 p-3">
             {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
         {% endif %}
         <style>
          li {
           list-style-type: none; 
          ul {
           margin-left: 20;
           padding-left: 20;
          }
         </style>
        <ul>
          <h4> Комментарии к записи</h4>
            {% for comment in comments %}
              <h5 class="mt">
                <li>
                <a href="{% url 'posts:profile' comment.author.username %}">
                 {{ comment.author.username }}
                </a>
              </h5>
                <h7>
                  {{comment.created|date:"d.m.Y H:i"}}
                </h7>
              <p>
              {{ comment.text }}
              </p>
               </li>
       {% endfor %} 
{% endblock %}
    </main>
  

yatube/templates/posts/profile.html
{%extends 'base.html'%}
{% load thumbnail %}
<title> {%block title %} Профайл пользователя {{author}} {% endblock %} </title>
    <main>
      {%block content %}    
      <div class="mb-5">
        <h2>Все посты пользователя {{ author.get_full_name }}</h2>
        <h4>Всего постов: {{ author.posts.count }}</h4>
        {% if user.is_authenticated %}
        {% if user.username != author.username %}
          {% if following %}
            <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button">
              Отписаться
            </a>
           {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
      {% endif %}
      </div>
        <article>
          {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
         {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
         <img class="card-img my-2" src="{{ im.url }}">
         {% endthumbnail %}
         <p>{{ post.text }} </p>
         {%if post.group%}  
         <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы</a>  
         {% endif %}  
         <a href= "{% url 'posts:post_detail' post.id %}"> Подробная информация </a>  
         {% if not forloop.last %}<hr>{% endif %}
       {% endfor %} 
        </article>       
        <hr>
        {% include 'posts/includes/paginator.html' %}
      </div>
      {% endblock %}
    </main>